{
    "id": "problem_25",
    "description": "\n\nThe problem is an IndexError that occurs when using multiprocessing. When running a program that utilizes multiprocessing to split tasks between multiple CPUs, an IndexError is raised when the system attempts to access an index that is out of range for the list of tasks assigned to each",
    "code": "import multiprocessing\n\ndef process_tasks(task_list):\n    for task in task_list:\n        print(task)\n\nif __name__ == '__main__':\n    task_list = [1, 2, 3]",
    "tags": [
        "IndexError",
        "multiprocessing",
        "Easy"
    ]
}