{
    "id": "problem_106",
    "description": "\n\nProblem: A RuntimeError is thrown when a tuple is being accessed with an index that is out of range.",
    "code": "# Create a tuple\nmy_tuple = (\"apple\", \"banana\", \"orange\")\n\n# Access the first item in the tuple\nfirst_item = my_tuple[0]\nprint(first_item) # Outputs: apple",
    "tags": [
        "RuntimeError",
        "tuple",
        "Easy"
    ]
}