{
    "id": "problem_84",
    "description": "\n\nProblem Description:\nAn IndentationError is thrown when a programmer attempts to append a line of code to the end of a function without properly indenting it. This causes the Python interpreter to not recognize the code as part of the function and thus throws the IndentationError.",
    "code": "# Define a sample list \nsample_list = [1, 2, 3] \n  \n# Appending the element 4 to the list \nsample_list.append(4) \n  \n# Printing the updated list \nprint(sample_list",
    "tags": [
        "IndentationError",
        "append",
        "Hard"
    ]
}