{
    "id": "problem_64",
    "description": "\n\nA Metaclass AssertionError is thrown when an attempt is made to create an instance of a metaclass that does not exist in the current scope. This error is raised when the code is attempting to instantiate a metaclass that is not defined in the current scope.",
    "code": "class MyClass(metaclass=type):\n    def __init__(self):\n        self.name = \"MyClass\"\n \n    def print_name(self):\n        print(self.name)\n \nobj = MyClass()\nobj",
    "tags": [
        "AssertionError",
        "Metaclass",
        "Medium"
    ]
}