{
    "id": "problem_36",
    "description": "\n\nProblem Description:\nWhen trying to create a new instance of a NamedTuple, a ValueError is raised indicating that the given values are not valid for the NamedTuple. This error occurs when the given values do not match the expected number of fields for the NamedTuple.",
    "code": "from collections import namedtuple\n\n# create a namedtuple\nBook = namedtuple('Book', ['title', 'author', 'year'])\n\n# create a list of books\nbooks = [\n    Book('To Kill a Mockingbird', 'Har",
    "tags": [
        "ValueError",
        "NamedTuple",
        "Easy"
    ]
}