{
    "id": "problem_24",
    "description": "\n\nWhen attempting to create a NamedTuple, the program produces an IndentationError. This is because the indentation of the NamedTuple is not consistent with the rest of the code, causing the program to be unable to recognize the NamedTuple as a valid object.",
    "output": ">>> from collections import namedtuple\n>>> MyTuple = namedtuple('MyTuple', ['name', 'age'])\n>>> person = MyTuple('John', 25)\n>>> person\nMyTuple(name='John', age=25)",
    "tags": [
        "IndentationError",
        "NamedTuple",
        "Easy"
    ]
}