{
    "id": "problem_84",
    "description": "\n\nProblem Description:\nAn IndentationError is thrown when a programmer attempts to append a line of code to the end of a function without properly indenting it. This causes the Python interpreter to not recognize the code as part of the function and thus throws the IndentationError.",
    "output": "[1, 2, 3, 4]",
    "tags": [
        "IndentationError",
        "append",
        "Hard"
    ]
}